### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by mleduque** [TankerHQ/sdk-native#1]
## Issue

The github repository lacks any hint on how the project is to be built.
The README.md doesn't tell anything about building.
There is no BUILDING file either.

I don't think I found any HTML documentation for sdk-native either (only other languages are documented AFAIK).

## Environment

Tanker SDK version: github master
Compiler: NA
Compiler version: NA
Conan version:NA
OS: linux

**Comment by mleduque** [comment]
I think it uses a build system called conan (didn't know it) https://conan.io/
This should use a file named conanfile.txt but I don't think there is one, I only found a conanfile.py (?)

**Comment by mleduque** [comment]
Or should I just use cmake ?

**Comment by jeremad** [comment]
Hello!

We published the code of this repository, and we are currently working on the possibility for someone outside the company to compile it, however it is not possible yet.

It seems you'd like a rust binding of this project, if this is the case, I'd advise you to reach us by email: contact@tanker.io

**Comment by jeremad** [comment]
hello @mleduque , I didn't hear from you again. If you have interest in a rust SDK, we'd like to discuss this with you!
